services:
  db:
    image: pgvector/pgvector:pg18-trixie
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
